export type Lang = "id" | "en";

const id = {
  lede: "Pilih foto terbaik dari satu folder sampai jumlahnya pas dengan target.",
  folder: "Folder",
  browse: "Telusuri…",
  browseTitle: "Pilih folder foto",
  placeholder: "D:\\Foto\\Liburan",
  target: "Target",
  photos: "foto",
  more: "Tambah",
  less: "Kurangi",
  sortBy: "Urutkan",
  sorts: { name: "Nama", taken: "Tanggal diambil", mtime: "Tanggal diubah", size: "Ukuran file", random: "Acak" },
  footnote: "Foto terpilih dipindah ke subfolder selected. Sesi yang belum selesai otomatis dilanjutkan.",
  start: "Mulai menyortir",
  language: "Bahasa",
  layout: "Susunan foto",
  horizontal: "Horizontal",
  vertical: "Vertikal",
  undo: "Urungkan",
  changeFolder: "Ganti folder",
  doneTitle: (n: number) => `${n} foto terpilih`,
  doneBody: "Semua foto pilihan ada di",
  undoLast: "Urungkan terakhir",
  sortAnother: "Sortir folder lain",
  modeTitle: { fill: "Pilih kandidat", reduce: "Saring pilihan", rescue: "Tambah dari yang ditolak" },
  modeHelp: {
    fill: "Foto yang dipilih dipindah ke folder selected.",
    reduce: "Foto yang ditolak dikembalikan ke folder awal.",
    rescue: "Foto yang ditolak di ronde sebelumnya. Yang dipilih masuk lagi ke folder selected.",
  },
  ofTarget: (n: number) => `dari target ${n}`,
  noPreview: "Pratinjau tidak tersedia",
  current: "Sedang dinilai",
  next: "Berikutnya",
  roundProgress: "Progres ronde",
  round: (n: number) => `Ronde ${n}`,
  position: (i: number, n: number) => `${i} dari ${n}`,
  reject: "Tolak",
  pick: "Pilih",
  zoom: "Perbesar",
  spaceKey: "Spasi",
  share: "Bagikan",
  sharing: "Membuat link…",
  shareTitle: "Bagikan untuk voting",
  shareBody: "Orang dengan link dan PIN ini bisa menyortir sendiri semua foto di folder ini lalu mengirim pilihannya. Foto tidak dipindah sampai Anda menyetujui.",
  link: "Link",
  pin: "PIN",
  copy: "Salin",
  copied: "Tersalin",
  stopShare: "Stop berbagi",
  close: "Tutup",
  shareOn: "Berbagi aktif",
  guestResults: (n: number) => `Hasil tamu (${n})`,
  reviewTitle: "Hasil tamu",
  reviewBody: (n: number) => `${n} tamu sudah mengirim. Foto dengan suara terbanyak sudah dicentang sebagai saran. Klik foto untuk mengubah centang.`,
  noSubmissions: "Belum ada kiriman dari tamu. Anda tetap bisa memilih sendiri dari semua foto.",
  voteCount: (n: number) => `${n} suara`,
  needExactly: (n: number) => `Centang tepat ${n} foto untuk menyetujui.`,
  useSuggestion: "Pakai saran",
  rejectResults: "Tolak hasil",
  approve: "Setujui & terapkan",
  approveConfirm: (n: number) => `Folder selected akan berisi tepat ${n} foto yang dicentang. Foto lain dikembalikan ke folder awal. Lanjutkan?`,
  back: "Kembali",
  updateTitle: (v: string) => `Photo Sorter ${v} tersedia`,
  updateBody: "App akan ditutup, diperbarui, lalu dibuka lagi. Sesi sortir tetap tersimpan di folder.",
  later: "Nanti",
  updateNow: "Perbarui sekarang",
  guest: "Tamu",
  note: {
    unchanged: () => "Ronde sebelumnya tidak mengubah jumlah foto. Pilih lebih ketat.",
    short: (n: string) => `Kurang ${n} foto. Pilih lagi dari foto yang ditolak di ronde sebelumnya.`,
  },
  error: {
    folder_not_found: (p: string) => `Folder tidak ditemukan: ${p}`,
    target_range: (a: string) => {
      const [max, total] = a.split(":");
      return `Target harus 1 sampai ${max} (total foto ${total}).`;
    },
    no_photos: () => "Tidak ada foto untuk disortir.",
    no_session: () => "Belum ada sesi.",
    move_failed: (a: string) => `Gagal memindah ${a}`,
    cloudflared_missing: () => "cloudflared belum terpasang. Jalankan: winget install Cloudflare.cloudflared, lalu buka ulang app.",
    target_mismatch: (n: string) => `Centang tepat ${n} foto.`,
    tunnel_failed: (a: string) => `Gagal membuat link online (${a}). Cek koneksi internet lalu coba lagi.`,
  },
};

const en: typeof id = {
  lede: "Pick the best photos in a folder until you reach your target count.",
  folder: "Folder",
  browse: "Browse…",
  browseTitle: "Choose a photo folder",
  placeholder: "D:\\Photos\\Holiday",
  target: "Target",
  photos: "photos",
  more: "Increase",
  less: "Decrease",
  sortBy: "Sort by",
  sorts: { name: "Name", taken: "Date taken", mtime: "Date modified", size: "File size", random: "Random" },
  footnote: "Picked photos move to a selected subfolder. An unfinished session resumes automatically.",
  start: "Start sorting",
  language: "Language",
  layout: "Photo layout",
  horizontal: "Horizontal",
  vertical: "Vertical",
  undo: "Undo",
  changeFolder: "Change folder",
  doneTitle: (n) => `${n} photos picked`,
  doneBody: "All picked photos are in",
  undoLast: "Undo last",
  sortAnother: "Sort another folder",
  modeTitle: { fill: "Pick candidates", reduce: "Narrow down", rescue: "Add back from rejects" },
  modeHelp: {
    fill: "Picked photos move to the selected folder.",
    reduce: "Rejected photos go back to the original folder.",
    rescue: "Photos rejected last round. Picked ones move back into the selected folder.",
  },
  ofTarget: (n) => `of target ${n}`,
  noPreview: "No preview available",
  current: "Reviewing",
  next: "Next",
  roundProgress: "Round progress",
  round: (n) => `Round ${n}`,
  position: (i, n) => `${i} of ${n}`,
  reject: "Reject",
  pick: "Pick",
  zoom: "Zoom",
  spaceKey: "Space",
  share: "Share",
  sharing: "Creating link…",
  shareTitle: "Share for voting",
  shareBody: "Anyone with this link and PIN can sort every photo in this folder on their own and send their picks. Nothing moves until you approve.",
  link: "Link",
  pin: "PIN",
  copy: "Copy",
  copied: "Copied",
  stopShare: "Stop sharing",
  close: "Close",
  shareOn: "Sharing on",
  guestResults: (n) => `Guest results (${n})`,
  reviewTitle: "Guest results",
  reviewBody: (n) => `${n} guests sent their picks. The most-voted photos are checked as a suggestion. Click a photo to change it.`,
  noSubmissions: "No guest has sent picks yet. You can still choose from all photos yourself.",
  voteCount: (n) => `${n} votes`,
  needExactly: (n) => `Check exactly ${n} photos to approve.`,
  useSuggestion: "Use suggestion",
  rejectResults: "Reject results",
  approve: "Approve & apply",
  approveConfirm: (n) => `The selected folder will hold exactly the ${n} checked photos. Other photos go back to the original folder. Continue?`,
  back: "Back",
  updateTitle: (v) => `Photo Sorter ${v} is available`,
  updateBody: "The app closes, updates and reopens. Your sorting progress stays in the folder.",
  later: "Later",
  updateNow: "Update now",
  guest: "Guest",
  note: {
    unchanged: () => "Last round didn't change the count. Be stricter.",
    short: (n) => `${n} photos short. Pick again from last round's rejects.`,
  },
  error: {
    folder_not_found: (p) => `Folder not found: ${p}`,
    target_range: (a) => {
      const [max, total] = a.split(":");
      return `Target must be 1 to ${max} (${total} photos total).`;
    },
    no_photos: () => "No photos to sort.",
    no_session: () => "No session yet.",
    move_failed: (a) => `Couldn't move ${a}`,
    cloudflared_missing: () => "cloudflared isn't installed. Run: winget install Cloudflare.cloudflared, then reopen the app.",
    target_mismatch: (n) => `Check exactly ${n} photos.`,
    tunnel_failed: (a) => `Couldn't create the online link (${a}). Check your internet connection and try again.`,
  },
};

export const strings = { id, en };

/** Backend messages arrive as `code:arg`; unknown ones (raw OS errors) pass through. */
export function translate(dict: Record<string, (arg: string) => string>, msg: string): string {
  const i = msg.indexOf(":");
  const code = i < 0 ? msg : msg.slice(0, i);
  return dict[code] ? dict[code](i < 0 ? "" : msg.slice(i + 1)) : msg;
}
