LangString addOrReinstall ${LANG_INDONESIAN} "Tambah/Pasang ulang komponen"
LangString alreadyInstalled ${LANG_INDONESIAN} "Sudah Terpasang"
LangString alreadyInstalledLong ${LANG_INDONESIAN} "${PRODUCTNAME} ${VERSION} sudah terpasang. Pilih operasi yang ingin dilakukan lalu klik Next untuk melanjutkan."
LangString appRunning ${LANG_INDONESIAN} "{{product_name}} sedang berjalan! Tutup aplikasinya terlebih dahulu lalu coba lagi."
LangString appRunningOkKill ${LANG_INDONESIAN} "{{product_name}} sedang berjalan!$\nKlik OK untuk menutupnya"
LangString chooseMaintenanceOption ${LANG_INDONESIAN} "Pilih opsi pemeliharaan yang ingin dilakukan."
LangString choowHowToInstall ${LANG_INDONESIAN} "Pilih cara memasang ${PRODUCTNAME}."
LangString createDesktop ${LANG_INDONESIAN} "Buat pintasan di desktop"
LangString dontUninstall ${LANG_INDONESIAN} "Jangan hapus instalasi"
LangString dontUninstallDowngrade ${LANG_INDONESIAN} "Jangan hapus instalasi (turun versi tanpa menghapus instalasi dinonaktifkan untuk installer ini)"
LangString failedToKillApp ${LANG_INDONESIAN} "Gagal menutup {{product_name}}. Tutup aplikasinya terlebih dahulu lalu coba lagi"
LangString installingWebview2 ${LANG_INDONESIAN} "Memasang WebView2..."
LangString newerVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} yang lebih baru sudah terpasang! Memasang versi lama tidak disarankan. Jika tetap ingin memasang versi lama, sebaiknya hapus instalasi versi sekarang terlebih dahulu. Pilih operasi yang ingin dilakukan lalu klik Next untuk melanjutkan."
LangString older ${LANG_INDONESIAN} "lebih lama"
LangString olderOrUnknownVersionInstalled ${LANG_INDONESIAN} "Versi ${PRODUCTNAME} $R4 terpasang di sistem Anda. Disarankan menghapus instalasi versi sekarang sebelum memasang. Pilih operasi yang ingin dilakukan lalu klik Next untuk melanjutkan."
LangString silentDowngrades ${LANG_INDONESIAN} "Turun versi dinonaktifkan untuk installer ini, instalasi senyap tidak bisa dilanjutkan. Gunakan installer dengan tampilan grafis.$\n"
LangString unableToUninstall ${LANG_INDONESIAN} "Tidak dapat menghapus instalasi!"
LangString uninstallApp ${LANG_INDONESIAN} "Hapus instalasi ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_INDONESIAN} "Hapus instalasi sebelum memasang"
LangString unknown ${LANG_INDONESIAN} "tidak diketahui"
LangString webview2AbortError ${LANG_INDONESIAN} "Gagal memasang WebView2! Aplikasi tidak bisa berjalan tanpanya. Coba jalankan ulang installer."
LangString webview2DownloadError ${LANG_INDONESIAN} "Error: Gagal mengunduh WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_INDONESIAN} "Bootstrapper WebView2 berhasil diunduh"
LangString webview2Downloading ${LANG_INDONESIAN} "Mengunduh bootstrapper WebView2..."
LangString webview2InstallError ${LANG_INDONESIAN} "Error: Pemasangan WebView2 gagal dengan kode keluar $1"
LangString webview2InstallSuccess ${LANG_INDONESIAN} "WebView2 berhasil dipasang"
LangString deleteAppData ${LANG_INDONESIAN} "Hapus data aplikasi"